config/routes.rb
Rails.application.routes.draw do
 

  root 'static_pages#home'
  get '/index', to: 'static_pages#index'
  get '/nouveaucorsaire', to: 'users#new'
  get  '/signup',  to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def index
  end

  def nouveaucorsaire
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Index des corsaires",  index_path  %></li>
        <li><%= link_to "Nouveau corsaire", nouveaucorsaire_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpCorsaires</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les corsaires 🎓
  </h3>
  <%= link_to "Enregistre-toi !", nouveaucorsaire_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/static_pages/nouveaucorsaire.html.erb
<h1>StaticPages#nouveaucorsaire</h1>
<p>Find me in app/views/static_pages/nouveaucorsaire.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>